/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ISvgClock: typeof import('~icons/svg/clock')['default']
    ISvgClose: typeof import('~icons/svg/close')['default']
    ISvgEyeHidden: typeof import('~icons/svg/eye-hidden')['default']
    ISvgEyeVisible: typeof import('~icons/svg/eye-visible')['default']
    ISvgMenu: typeof import('~icons/svg/menu')['default']
    ISvgSearch: typeof import('~icons/svg/search')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
