name: Bug Report
description: Create a report to help us improve
title: "Bug: {short description}"
labels: [bug, needs triage]
body:
  - type: markdown
    attributes:
      value: |
        Please take the time to fill out this bug report. Thanks!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you saw
    validations:
      required: true
  - type: textarea
    id: what-was-expected
    attributes:
      label: What did you expect to happened?
      placeholder: What were you expecting?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Step(s) to Reproduce
      description: Tell us how you came across this
      placeholder: ex. I was on X page, and clicked Y thing
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Were you on mobile when this happened?
      multiple: false
      options:
        - No
        - Yes
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Brave
        - Chrome
        - Firefox
        - Microsoft Edge
        - Opera
        - Safari
        - Vivaldi
        - Other
    validations:
      required: true
  - type: input
    id: other-browser
    attributes:
      label: Other Browser
      description: If you selected 'Other', please type the name of the browsers you're using/seeing the problem on
      placeholder: ex. Dolphin, Puffin, Samsung Internet, etc.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: javascript
